### ISSUE TITLE
Repeating the posts and media on telegram

### ISSUE THREAD

**Issue by Dan7h3x** [Massolari/reddit_to_telegram#5]
Hey buddy, can you handle the problem of sometimes repeating a post and its media on telegram, its very annoying. Thanks

**Comment by Massolari** [comment]
Hmm... Problably your problem is being caused when a post is divided in messages to send to telegram and one of the messages fails, so the post isn't registered as sent and the script tries to send it again later 🤔 

I'll take a look at this

**Comment by Dan7h3x** [comment]
> Hmm... Problably your problem is being caused when a post is divided in messages to send to telegram and one of the messages fails, so the post isn't registered as sent and the script tries to send it again later 🤔
> 
> I'll take a look at this

Yeah, actually if you take a look at telegram channel for few post before there is a situation that have repeated my post on r/neovim so many times. Thanks

**Comment by Massolari** [comment]
I found it, and it confirmed my assumptions.
I've pushed a change that will prevent this from happening again.
Now, even when a post fails, the script won't try sending it again.
I also improved the logging a bit so it'll be easier to fix when a post fails to send.
